spring:
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
    template-resolver-order: 0
  resources: 
    static-locations: classpath:static/
  h2:
    console:
      enabled: true
  jpa:
    hibernate.ddl-auto: update # create-drop
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
